OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: goodchar.com
    Specs:
      - Hostname: orderer


PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: LocalNGO1
    Domain: localngo1.goodchar.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2

  # ---------------------------------------------------------------------------
  # Org2
  # ---------------------------------------------------------------------------
  - Name: LocalNGO2
    Domain: localngo2.goodchar.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2

  # ---------------------------------------------------------------------------
  # Org3
  # ---------------------------------------------------------------------------
  - Name: GC
    Domain: gc.goodchar.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2
  